baseURL = 'https://ignacio.tech'
languageCode = 'en-us'
title = 'ignacio.tech'
theme = 'ignaciotech'

[params]
  description = "Ignacio - Android Developer & AI Engineer with 5+ years programming experience. Specialized in mobile development, machine learning automation, and open-source projects in Valencia, Spain."
  author = "Ignacio"
  email = "hi@ignacio.tech"
  
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "#about"
    weight = 2
  [[menu.main]]
    name = "Experience"
    url = "#experience"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "#projects"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "#contact"
    weight = 5
