defaultContentLanguage = 'en'
theme = 'ignaciotech'
enableRobotsTXT = true

# Sitemap configuration
[sitemap]
  changefreq = 'weekly'
  priority = 0.5
  filename = 'sitemap.xml'

[params]
  author = "Ignacio L. D."
  description = "Android & AI Developer"
  location = "Valencia, Spain"
  
  # Theme customization
  darkModeEnabled = true
  showFeaturedImage = true
  
  # Blog settings
  postsPerPage = 10
  showReadingTime = true
  showCategories = true
  
  # Projects settings
  projectsEnabled = true
  maxFeaturedProjects = 3

[params.social]
  linkedin = "https://linkedin.com/in/IgnacioLD"
  mastodon = "https://mastodon.social/@shirabit"
  github = "https://github.com/IgnacioLD"
  email = "hi@ignacio.tech"
  x = "https://x.com/shirabit"

[languages]
  [languages.en]
    languageCode = 'en-us'
    title = 'Ignacio L. D. - AI Engineer & Android Developer - Valencia, Spain'
    weight = 1
    [languages.en.params]
      description = "AI Engineer & Android Developer in Valencia, Spain. Building intelligent mobile solutions with generative AI and leading open source projects."
      author = "Ignacio L. D."
      email = "hi@ignacio.tech"
    [[languages.en.menu.main]]
      name = "Home"
      url = "/"
      weight = 1
    [[languages.en.menu.main]]
      name = "Blog"
      url = "/blog/"
      weight = 2
    [[languages.en.menu.main]]
      name = "All Projects"
      url = "/projects/"
      weight = 3

#  [languages.es]
#    languageCode = 'es-es'
#    title = 'Ignacio L. D.'
#    weight = 2
#    [languages.es.params]
#      description = "Ignacio L. D. - Desarrollador Android e Ingeniero de IA con más de 5 años de experiencia en programación. Especializado en desarrollo móvil, automatización de aprendizaje automático y proyectos de código abierto en Valencia, España."
#      author = "Ignacio L. D."
#      email = "hi@ignacio.tech"
#    [[languages.es.menu.main]]
#      name = "Inicio"
#      url = "/"
#      weight = 1
#    [[languages.es.menu.main]]
#      name = "Blog"
#      url = "/blog/"
#      weight = 2
#    [[languages.es.menu.main]]
#      name = "Todos los Proyectos"
#      url = "/projects/"
#      weight = 3
